### ISSUE TITLE
Situations which lead to coercion

### ISSUE THREAD

**Issue by iancoleman** [Frogolocalypse/Bitcoin_non_coerced_hardfork#1]
I have a lot of questions about this proposal but I would like to start by asking what you think about these situations after NCHF is active, which I think lead to coercion:

1. A merchant shows a customer a bitcoin address, and receives payment. How does the merchant know which hardfork this arrives at? It seems they are coerced into checking all forks, even if the merchant only wants to support the original fork.

1. A new user has coins on a newer hardfork and wants to send it to an old user on the original fork. The old user is coerced to the new fork, since the coins can't be sent back to the original fork.

I don't really see how original users are able to just ignore the hardforks.

**Comment by Frogolocalypse** [comment]
1.  The proposal would be to allow the spender to nominate which chain they want to send the transaction from, because it is the spenders coins being located in either the old chain or the new chain that defines where the transaction exists.  If the merchant only accepts new chain transactions, the act of spending the transaction will initiate a value migration to the new chain.

2a.  It is not possible for users to spend new chain coins on the old chain.  It should, however, be possible to develop an atomic swap market between the new chain and the old chain at an exchange rate set by the market.

2b. 'sent back' isn't really a concept that needs to be addressed here.  There is no contract when bitcoin is transacted that requires the receiver to specify how they would the coins could be returned.  They have relinquished all ownership of how those coins are utilized.  It is up to each individual user to determine what chain they want to send transactions from, and which chain to record their transactions on.  It is non-coercive, because you can't force someone to use a chain.  A merchant should be able to choose to only accept old chain coins, new chain coins, or old chain coins as new chain coins.

The premise of a hard-fork is that it has broad consensus, having a feature-set that is desirable, or it will not be proposed in the first place.  The NCHF proposal makes no comment on the specifics of the hard-fork architecture of the new chain.  The proposal demonstrates that it even after the hard-fork, bitcoin may still be safely used without leading to a chain-split that requires a node owner to change their node client software.

I believe the architecture, therefore, is non-coercive.

**Comment by Frogolocalypse** [comment]
I have updated the main document to reflect the definition of coercion in the context of bitcoin and the NCHF.

Do you agree that this addresses the issue? If you think so, I will include the information about the transactions framework to the main document.

**Comment by iancoleman** [comment]
The definition helps.

> The proposal demonstrates that even after the hard-fork, bitcoin may still be **safely used**

I still think a user who wants to receive coins on the original chain from someone on the new chain is unable to **use** bitcoin in their original understanding of the word 'use'. They are coerced to follow (or at the very least know the existence of) any new chain.

I also think without some way for the original chain user to know which chain the sender is on (or tell that user which chain to use), they're no longer **safe** to use bitcoin.

So to me, this doesn't seem like a way to upgrade bitcoin via hardfork in a way that retains the current ability to use bitcoin and be safe doing so. I'm not sure it's possible. But it's all a bit academic, since it depends what is considered 'using bitcoin' and 'safe use', to which I am ultra-conservative in my definition.

But the issue *has* been resolved because coercion is now clearly defined, so I'll close this.
